### ISSUE TITLE
AD5263 support possible?

### ISSUE THREAD

**Issue by pe1rmg** [RobTillaart/AD5263#1]
Hi Rob,

Would it be possible to include support for the AD5263?
I am specifically looking for an Arduino library which supports a 4 channel, 256 step digital potentiometer, with I2C interface.... (It needs to be compatible with an RP2040 microcontroller, but I do not see any issue with the libraries of you I have been using so far, so I expect that will be no problem)

If needed, I am willing to sponsor the development of a library. :-)  (In that case please contact me at my username AT gmail)

Thanks! 
Paul

**Comment by RobTillaart** [comment]
Thanks for the issue. 
Such a library should be possible, need to the datasheet (download), a way to test (you?) and some time.

Not seen the datasheet, I assume it is a straightforward device so it should take 4-8 hrs to set up the things incl build infra and initial documentation.
Will download datasheet later today to see if there are surprises.

Do you need it fast?

**Comment by RobTillaart** [comment]
- downloaded datasheet
- created a placeholder => https://github.com/RobTillaart/AD5263

I move this issue to that repository.

**Comment by pe1rmg** [comment]
> Thanks for the issue. Such a library should be possible, need to the datasheet (download), a way to test (you?) and some time.
> 
> Not seen the datasheet, I assume it is a straightforward device so it should take 4-8 hrs to set up the things incl build infra and initial documentation. Will download datasheet later today to see if there are surprises.
> 
> Do you need it fast?

Hi Rob,

Thanks for the very rapid response :-) .
There is from my side no real rush, I am at 90% of developing the diagram / PCB where I need such a device, but I want to make sure that before I finish the design, the software support is there. Of course I am very happy to test it out for you using my design, but that will be done hopefully by December. So there is no need to rush this!

Thanks a lot!
Paul

**Comment by RobTillaart** [comment]
Moved some tasks in my agenda
Stripped and renamed AD524X into develop branch.
Build is running

**Comment by RobTillaart** [comment]
@pe1rmg 
Build looks stable so next step is hardware testing.
Can you do HW tests on bread board?

**Comment by pe1rmg** [comment]
@RobTillaart Let me create a test PCB, and get it on order. I have no AD5263 available at this moment, but it is easy enough to create a simple test PCB and have it assembled.  I will get you also the PCB, just drop me an email PE1RMG AT gmail .
(I will be in Holland the end of the month, so it is easy enough to get it to you)

**Comment by RobTillaart** [comment]
@pe1rmg 
I'm going to release a 0.1.0 version today so other people can provide feedback too.

**Comment by RobTillaart** [comment]
Released 0.1.0 
Published on platformIO and Arduino License manager.

**Comment by RobTillaart** [comment]
Note to myself.
Performance wise it might be interesting to investigate the SPI interface too (first have I2C stable, tested and verified).
This is faster than I2C and allows daisy chaining. The only functional difference is that it does not support the O1 O2 .

**Comment by RobTillaart** [comment]
A new develop branch is created, 
mostly minor edits / cleanup

**Comment by RobTillaart** [comment]
Merged develop into master
Released 0.1.1 => build-Ci is running.

**Comment by RobTillaart** [comment]
Released 0.1.2 after hardware test.
